name: Fetch Nullplatform Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets-and-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Nullplatform Secrets and Variables
        id: fetch-secrets
        uses: nullplatform/github-action-secrets-and-variables@v1
        with:
          application-id: your-app-id
          api-key: ${{ secrets.NULLPLATFORM_API_KEY }}

      - name: Display Secrets and Variables
        run: |
          echo "Retrieved Secrets and Variables:"
          echo "Variable Name: your-variable-name"
          echo "Variable Value: ${{ steps.fetch-secrets.outputs.your-variable-name }}"
